# Generated by Django 6.0.6 on 2026-07-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, help_text='Snapshot AFTER change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, help_text='Snapshot BEFORE change', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Store FAQ", "Return Policy Details"', max_length=255)),
                ('file', models.FileField(upload_to='knowledge_base/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are searchable by the Support Agent.')),
                ('is_indexed', models.BooleanField(default=False, editable=False, help_text='Whether this document is currently embedded in Qdrant.')),
                ('chunk_count', models.IntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
