# Generated by Django 6.0.6 on 2026-07-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_content_type',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
